"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.expenditureRoutes = void 0;
const express_1 = require("express");
const ensureAuthenticate_1 = require("../middlewares/ensureAuthenticate");
const index_1 = require("./../controllers/Expenditure/CreateExpenditureController/index");
const index_2 = require("./../controllers/Expenditure/UpdateExpenditureByIdController/index");
const index_3 = require("./../controllers/Expenditure/GetAllExpenditureByWalletIdController/index");
const index_4 = require("./../controllers/Expenditure/DeleteExpenditureByIdController/index");
const index_5 = require("./../controllers/Expenditure/GetAllExpendituresByIdController/index");
const index_6 = require("./../controllers/Expenditure/GetUniqueExpenditureController/index");
const CheckExpenditureController_1 = require("./../controllers/Expenditure/CheckExpenditureController");
const expenditureRoutes = (0, express_1.Router)();
exports.expenditureRoutes = expenditureRoutes;
expenditureRoutes.post('/create', ensureAuthenticate_1.ensureAuthenticate, new index_1.CreateExpenditureController().handle);
expenditureRoutes.get('/get-one/:expenditureId', ensureAuthenticate_1.ensureAuthenticate, new index_6.GetUniqueExpenditureController().handle);
expenditureRoutes.get('/get-all-by-wallet/:walletId', ensureAuthenticate_1.ensureAuthenticate, new index_3.GetAllExpenditureByWalletIdController().handle);
expenditureRoutes.get('/get-all/:userId', ensureAuthenticate_1.ensureAuthenticate, new index_5.GetAllExpendituresByIdController().handle);
expenditureRoutes.put('/update/:expenditureId', ensureAuthenticate_1.ensureAuthenticate, new index_2.UpdateExpenditureByIdController().handle);
expenditureRoutes.put('/check/:expenditureId', ensureAuthenticate_1.ensureAuthenticate, new CheckExpenditureController_1.CheckExpenditureController().handle);
expenditureRoutes.delete('/delete/:expenditureId', ensureAuthenticate_1.ensureAuthenticate, new index_4.DeleteExpenditureByIdController().handle);
